import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import GlobalTransition from "./component/PageTransition";
import NavbarWOSwitch from "./component/navbarWOSwitch";
import Footer from "./component/footer";

// Inter 字體 - 用於內文
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// 使用 Variable 字體（一個檔案包含所有字重）
const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2", // 只需要這一個檔案
  variable: "--font-satoshi",
  display: "swap",
  weight: "300,900", // 支援的字重範圍
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${satoshi.variable} antialiased theme-dark`}
      >
        <NavbarWOSwitch />
        <GlobalTransition>{children}</GlobalTransition>
        <Footer />
      </body>
    </html>
  );
}
